version: '3.1'

services:
  backend:
    container_name: mizdooni-backend
    image: mizdooni-backend-local
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:lts
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mizdooni_ca5
    expose:
      - 3306
      - 33060

volumes:
  db_data:
