version: "3.1"

services:
  backend:
    container_name: mizdooni-backend
    image: mizdooniaf/mizdooni-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - spring-mysql

  db:
    image: mizdooniaf/mizdooni-db
    restart: always
    expose:
      - 3306

    networks:
      - spring-mysql

volumes:
  db_data:

networks:
  spring-mysql: {}
