apiVersion: v1
kind: Service
metadata:
  name: mizdooni-app
  labels:
    name: mizdooni-app-service
    app: mizdooni
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: mizdooni-frontend-pod
    app: mizdooni