apiVersion: v1
kind: Service
metadata:
  name: expose-mysql-service
spec:
  selector:
    app: mizdooni
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30006
  type: NodePort