apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: mizdooni
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mizdooni-db-pod
    app: mizdooni
