apiVersion: v1
kind: Service
metadata:
  name: mizdooni-app
  labels:
    name: mizdooni-app-service
    app: mizdooni
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
  selector:
    name: mizdooni-backend-pod
    app: mizdooni